# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rubygem-foreman_fog_proxmox.spec

# add or remove files that should be synced
files_to_sync:
  - rubygem-foreman_fog_proxmox.spec
  - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: foreman_fog_proxmox
# downstream (Fedora) RPM package name
downstream_package_name: rubygem-foreman_fog_proxmox

upstream_tag_template: v{version}

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec -O rubygem-foreman_fog_proxmox.spec"
  get-current-version:
    - ruby -rrubygems -e 'puts Gem::Specification::load(Dir.glob("*.gemspec").first).version'
  create-archive:
    - gem build foreman_fog_proxmox.gemspec
    - bash -c "ls -1t ./foreman_fog_proxmox-*.gem | head -n 1"

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      rhel-9:
        additional_modules: "foreman-devel:el9"
        additional_repos:
          - https://yum.theforeman.org/releases/nightly/el9/x86_64/
          - https://yum.theforeman.org/plugins/nightly/el9/x86_64/

  - <<: *copr
    trigger: commit
    branch: master
    owner: '@theforeman'
    project: develop

srpm_build_deps:
  - wget
  - rubygems
