Rails:
  Enabled: true

# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# TODO: try to refactor concerned code
Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 322

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 112

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 12

Metrics/LineLength:
  Max: 200 # TODO: discuss and set this

Naming/MethodName:
  Description: From foreman's rubocop-config. Neccessary for overloading methods in foreman.
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: Apparently, Deface hates frozen string literals
  Exclude:
    - 'app/overrides/compute_resources_vms/form/*.rb'

Style/Next:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
